"""Atualização tabela vendedores e rota autentication

Revision ID: 44c74fc10913
Revises: a8dc1d72f53a
Create Date: 2025-04-01 11:15:04.206051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c74fc10913'
down_revision: Union[str, None] = 'a8dc1d72f53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendedores', sa.Column('matricula', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendedores', 'matricula')
    # ### end Alembic commands ###
