"""Primeira migração - criando tabelas iniciais

Revision ID: 5a8b0d4c0ee9
Revises: 
Create Date: 2025-03-24 20:02:59.031773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8b0d4c0ee9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('código_do_produto', sa.Integer(), nullable=True),
    sa.Column('nome_do_produto', sa.String(), nullable=True),
    sa.Column('preço_do_produto', sa.Float(), nullable=True),
    sa.Column('quantidade_do_produto', sa.Integer(), nullable=True),
    sa.Column('detalhes_do_produto', sa.String(), nullable=True),
    sa.Column('produto_disponivel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    # ### end Alembic commands ###
